name: Push workflow for release branches
on:
  push:
    branches:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}

jobs:
  bump-version:
    name: Bump and Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Bump and Tag
        id: bump_and_tag
        uses: konsentus/action.bump-version-and-tag@master

      - name: Release
        if: github.ref == 'refs/heads/main'
        uses: konsentus/action.create-release@master
        with:
          new_version_tag: ${{ steps.bump_and_tag.outputs.new_version_tag }}
